server:
  port: 8080
  redis:
    host: localhost
    port: 6379

  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 600000
      use-key-prefix: false



# Application logging
logging:
  level:
    root: WARN
    org.springframework: INFO
    uk.co.pantasoft.fhr: INFO

service:
  client:
    foodhygieneRating:
      uri: http://api.ratings.food.gov.uk

