version: 2.0
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PSW
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies
      - run: gradle dependencies
      - run: gradle test
      - run: gradle build
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run:
          name: Creating docker image
          command: |
            gradle docker
            docker images
      - run:
          name: Pushing Docker image to Repository
          command: gradle dockerPush dockerTaglatest dockerPushlatest